version: '3.1'
services:
  itoken-admin:
    restart: always
    image: 192.168.75.128:5000/itoken-admin
    container_name: itoken-admin
    ports:
      - 8084:8084
    networks:
      - cloud

networks:
  cloud:
    external:
      name: spring_cloud