version: '3.1'
services:
  itoken-config:
    restart: always
    image: 192.168.75.128:5000/itoken-config
    container_name: itoken-config
    ports:
      - 8888:8888
    networks:
      - cloud

networks:
  cloud:
    external:
      name: spring_cloud