version: '3.1'
services:
  itoken-eureka:
    restart: always
    image: 192.168.75.128:5000/itoken-eureka
    container_name: itoken-eureka
    ports:
      - 8761:8761
    networks:
      - cloud

networks:
  cloud:
    external:
      name: spring_cloud